import { Search, SlidersHorizontal, X } from 'lucide-react';
import type { OrderFilters as Filters } from '../../../types/order';

const emptyFilters: Filters = { id: '', status: '', assignmentStatus: '', orderType: '', vip: '', parentOnly: false };

export function OrderFilters({ value, onChange }: { value: Filters; onChange: (filters: Filters) => void }) {
  const update = <K extends keyof Filters>(key: K, next: Filters[K]) => onChange({ ...value, [key]: next });
  const activeCount = Object.values(value).filter(Boolean).length;
  return <section className="filters panel"><div className="filters-title"><SlidersHorizontal size={17} /><strong>Фильтры</strong>{activeCount > 0 && <span>{activeCount}</span>}</div><label className="search-field"><Search size={17} /><span className="sr-only">Поиск по ID</span><input inputMode="numeric" placeholder="ID заявки" value={value.id} onChange={(event) => update('id', event.target.value)} /></label><select aria-label="Статус заявки" value={value.status} onChange={(event) => update('status', event.target.value as Filters['status'])}><option value="">Все статусы заявки</option><option value="processed">Обработана</option><option value="await">Ожидает</option><option value="accept">Принята</option><option value="reject">Отклонена</option></select><select aria-label="Статус назначения" value={value.assignmentStatus} onChange={(event) => update('assignmentStatus', event.target.value as Filters['assignmentStatus'])}><option value="">Все назначения</option><option value="pending">Ожидание</option><option value="reserved">Резерв</option><option value="assigned">Назначена</option><option value="unassigned">Не назначена</option><option value="failed">Ошибка</option></select><select aria-label="Тип заявки" value={value.orderType} onChange={(event) => update('orderType', event.target.value)}><option value="">Все типы</option><option>Проверка договора</option><option>Кредитный анализ</option><option>Повторная проверка</option><option>Консультация</option><option>Проверка сделки</option></select><select aria-label="VIP" value={value.vip} onChange={(event) => update('vip', event.target.value as Filters['vip'])}><option value="">VIP и обычные</option><option value="true">Только VIP</option><option value="false">Без VIP</option></select><label className="check-filter"><input type="checkbox" checked={value.parentOnly} onChange={(event) => update('parentOnly', event.target.checked)} />Только повторные</label>{activeCount > 0 && <button className="button ghost" onClick={() => onChange(emptyFilters)}><X size={15} />Сбросить</button>}</section>;
}

