import { useState } from 'react';
import { Check, ChevronDown, CircleX, GitBranch, Route, ShieldCheck } from 'lucide-react';
import type { DecisionTrace } from '../../../types/decisionTrace';
import { StatusBadge } from '../../../shared/components/StatusBadge';
import { formatBoolean, formatDuration, formatNumber } from '../../../shared/format';

type CandidateFilter = 'all' | 'passed' | 'excluded';

export function DecisionTraceView({ trace }: { trace: DecisionTrace }) {
  const [filter, setFilter] = useState<CandidateFilter>('all');
  const candidates = trace.candidates.filter((candidate) => filter === 'all' || (filter === 'passed' ? candidate.passedRules : !candidate.passedRules));
  return <div className="trace-stack">
    <section className={`trace-summary panel ${trace.selectedExecutorId ? 'success' : 'warning'}`}><div className="trace-summary-icon">{trace.selectedExecutorId ? <ShieldCheck /> : <CircleX />}</div><div><span className="section-kicker">Объяснение backend</span><h2>{trace.selectedExecutorId ? `Назначен исполнитель #${trace.selectedExecutorId}` : 'Назначение не состоялось'}</h2><p>{trace.explanation}</p><div className="trace-meta"><span>Обработка: <strong>{formatDuration(trace.processingTimeMs)}</strong></span><span>Модель: <strong>{trace.modelVersion ?? 'Не использовалась'}</strong></span><span>Правила: <strong>{trace.rulesVersion ?? 'Не указаны'}</strong></span></div></div></section>
    <section className="panel"><div className="panel-heading"><div><span className="section-kicker">Pipeline</span><h2>Этапы решения</h2></div><span className="trace-total">{trace.totalExecutors} → {trace.selectedExecutorId ? 1 : 0}</span></div><div className="stage-flow">{trace.stages.map((stage, index) => <div className="stage-item" key={`${stage.code}-${index}`}><span className="stage-index">{index + 1}</span><div><strong>{stage.label}</strong><span>{stage.inputCount} на входе · {stage.outputCount} на выходе</span>{stage.durationMs != null && <small>{formatDuration(stage.durationMs)}</small>}</div>{index < trace.stages.length - 1 && <span className="stage-line" />}</div>)}</div></section>
    {trace.parentReuse.attempted && <section className="panel parent-panel"><div className="panel-heading"><div><span className="section-kicker">Повторная заявка</span><h2><GitBranch size={20} /> Обработка parent_id</h2></div><span className={`result-pill ${trace.parentReuse.reused ? 'good' : 'neutral'}`}>{trace.parentReuse.reused ? 'Возврат выполнен' : 'Стандартное распределение'}</span></div><dl className="details-grid compact"><div><dt>Родительская заявка</dt><dd>#{trace.parentReuse.parentOrderId}</dd></div><div><dt>Предыдущий исполнитель</dt><dd>{trace.parentReuse.previousExecutorName ?? 'Не найден'}</dd></div><div><dt>Активен</dt><dd>{formatBoolean(trace.parentReuse.previousExecutorActive)}</dd></div><div><dt>Параметры совпали</dt><dd>{formatBoolean(trace.parentReuse.parametersMatched)}</dd></div><div><dt>Суточный лимит пропущен</dt><dd>{formatBoolean(trace.parentReuse.dailyLimitIgnored)}</dd></div><div><dt>Причина fallback</dt><dd>{trace.parentReuse.reason ?? 'Не требуется'}</dd></div></dl></section>}
    <section className="panel table-panel candidates-panel"><div className="panel-heading candidate-heading"><div><span className="section-kicker">Проверка и ranking</span><h2>Кандидаты</h2></div><div className="segmented" aria-label="Фильтр кандидатов">{([['all', 'Все'], ['passed', 'Прошедшие'], ['excluded', 'Исключённые']] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div></div><div className="table-scroll"><table><thead><tr><th>Исполнитель</th><th>Активен</th><th>Правила</th><th>Rank score</th><th>Confirmed</th><th>Pending</th><th>Effective</th><th>Reservation</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.executorId} className={candidate.selected ? 'selected-candidate' : ''}><td><strong>{candidate.executorName}</strong><small>#{candidate.executorId}</small>{candidate.selected && <span className="selected-label"><Check size={13} />Выбран</span>}</td><td>{candidate.active ? 'Да' : 'Нет'}</td><td>{candidate.passedRules ? <span className="pass-mark"><Check size={14} />Пройдены</span> : <details className="rules-details"><summary><CircleX size={14} />{candidate.failedRules.length} причин <ChevronDown size={14} /></summary><ul>{candidate.failedRules.map((rule, index) => <li key={`${rule.ruleId}-${index}`}><strong>{rule.ruleName ?? rule.ruleId ?? 'Правило'}</strong><span>{rule.reason}</span></li>)}</ul></details>}{candidate.dailyLimitReached && <span className="limit-note">Лимит достигнут</span>}</td><td>{candidate.rankScore == null ? 'Нет данных' : candidate.rankScore.toFixed(2)}</td><td>{formatNumber(candidate.confirmedWeight)}</td><td>{formatNumber(candidate.pendingWeight)}</td><td><strong>{formatNumber(candidate.effectiveLoad)}</strong></td><td><StatusBadge status={candidate.reservationResult} /></td></tr>)}</tbody></table></div>{candidates.length === 0 && <p className="inline-empty"><Route size={18} />В этой группе нет кандидатов.</p>}</section>
  </div>;
}

